### ISSUE TITLE
RateLimiter.hit always returns :ok

### ISSUE THREAD

**Issue by ivanpetrovic** [farhadi/rate_limiter#1]
Hi,

I am trying to trigger RateLimiter.hit to return :error but it never happens.
I am using the example from the readme.

```
rate_limiter = RateLimiter.new("test_bucket", 60000, 5)
case RateLimiter.hit(rate_limiter) do
   :ok ->
     # limit not reached yet
     :conn
        
   :error ->
     render_error(conn)
 end
```

Thanks.

**Comment by farhadi** [comment]
`RateLimiter.hit/1` returns error tuple `{:error, eta}`, and eta is the remaining time in milliseconds.
